apiVersion: apps/v1
kind: Deployment
metadata:
  name: faq-deployment
  labels:
    app: faq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faq
  template:
    metadata:
      labels:
        app: faq
    spec:
      containers:
      - name: faq
        image: madhavikola/faqsite:v1
        ports:
        - containerPort: 80

